default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= 'postgres' %>
  database: <%= ENV["POSTGRESQL_DATABASE"] || 'covid-19_development' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>
development:
  <<: *default
test:
  <<: *default
  database: <%= ENV["JENKINS_DATABASE"] || 'covid-19_test' %>
production:
  <<: *default
